apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: localstack-lab
  namespace: flux-system

spec:
  interval: 1m
  approvePlan: auto

  path: ./infrastructure/localstack

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  backendConfig:
    disable: true
